"""add_prekeys

Revision ID: 0d4c4236b249
Revises: 408279214832
Create Date: 2026-05-30 00:26:56.197123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4c4236b249'
down_revision: Union[str, Sequence[str], None] = '408279214832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device_prekey_bundles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('identity_key', sa.Text(), nullable=False),
    sa.Column('signed_prekey', sa.Text(), nullable=False),
    sa.Column('signed_prekey_signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'device_id')
    )
    with op.batch_alter_table('user_device_prekey_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_device_prekey_bundles_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_device_prekey_bundles_user_id'), ['user_id'], unique=False)

    op.create_table('user_one_time_prekeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('key_value', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_one_time_prekeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_one_time_prekeys_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_one_time_prekeys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_one_time_prekeys_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_one_time_prekeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_one_time_prekeys_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_one_time_prekeys_id'))
        batch_op.drop_index(batch_op.f('ix_user_one_time_prekeys_device_id'))

    op.drop_table('user_one_time_prekeys')
    with op.batch_alter_table('user_device_prekey_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_prekey_bundles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_device_prekey_bundles_device_id'))

    op.drop_table('user_device_prekey_bundles')
    # ### end Alembic commands ###
