"""add_comment_likes_columns

Revision ID: 1cb317046980
Revises: 62c65d9d9b3b
Create Date: 2026-06-08 00:23:25.580042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb317046980'
down_revision: Union[str, Sequence[str], None] = '62c65d9d9b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_likes_comment_id'), ['comment_id'], unique=False)
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_likes_comment_id'))
        batch_op.drop_column('comment_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
