"""add content reporting and audit logs

Revision ID: 62c65d9d9b3b
Revises: 553a88ea49e2
Create Date: 2026-06-07 22:40:27.738090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c65d9d9b3b'
down_revision: Union[str, Sequence[str], None] = '553a88ea49e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=True),
    sa.Column('unsubscribed', sa.Boolean(), nullable=True),
    sa.Column('esp_message_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_bounced'), ['bounced'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_esp_message_id'), ['esp_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_template'), ['template'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_email_log_user_template_sent', ['user_id', 'template', 'sent_at'], unique=False)

    op.create_table('moderation_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_audit_logs_id'), ['id'], unique=False)

    op.create_table('content_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_reports_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))

    with op.batch_alter_table('content_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_reports_id'))

    op.drop_table('content_reports')
    with op.batch_alter_table('moderation_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_audit_logs_id'))

    op.drop_table('moderation_audit_logs')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index('ix_email_log_user_template_sent')
        batch_op.drop_index(batch_op.f('ix_email_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_template'))
        batch_op.drop_index(batch_op.f('ix_email_log_sent_at'))
        batch_op.drop_index(batch_op.f('ix_email_log_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_esp_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_bounced'))

    op.drop_table('email_log')
    # ### end Alembic commands ###
