"""Add status to Transaction

Revision ID: 806aa527dfad
Revises: 7e1a2b3c4d5e
Create Date: 2026-05-15 22:20:56.665701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806aa527dfad'
down_revision: Union[str, Sequence[str], None] = '7e1a2b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_later',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watch_later', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_later_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_later_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_later_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('challenge_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_entries_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])
        batch_op.create_foreign_key(None, 'challenges', ['challenge_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_title'), ['title'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comments_video_id_created'))
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_video_id'), ['video_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user1_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user2_id'], ['id'])

    with op.batch_alter_table('discovered_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_categories_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('following_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_follows_follower_id'))
        batch_op.drop_index(batch_op.f('idx_follows_following_id'))
        batch_op.create_index(batch_op.f('ix_follows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_following_id'), ['following_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['following_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_likes_video_id'))
        batch_op.create_index(batch_op.f('ix_likes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_video_id'), ['video_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('partner_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_leads_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_leads_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_leads_id'), ['id'], unique=False)

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_wallet_id'), ['wallet_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'wallets', ['wallet_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_posts_owner_id'))
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_discovery_score'), ['discovery_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_original_post_id'), ['original_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'posts', ['original_post_id'], ['id'])

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_endpoint'), ['endpoint'], unique=True)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reposts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reposts_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)

    with op.batch_alter_table('sponsored_ads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsored_ads_id'), ['id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_wallet_id'), ['wallet_id'], unique=False)
        batch_op.create_foreign_key(None, 'wallets', ['wallet_id'], ['id'])

    with op.batch_alter_table('user_recommendation_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_recommendation_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_recommendation_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_unique_constraint(None, ['google_id'])
        batch_op.create_foreign_key(None, 'videos', ['pinned_video_id'], ['id'])

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_codes_id'), ['id'], unique=False)

    with op.batch_alter_table('video_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_interactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_interactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_interactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_interactions_video_id'), ['video_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_videos_created_at_desc'))
        batch_op.drop_index(batch_op.f('idx_videos_discovery_score'))
        batch_op.drop_index(batch_op.f('idx_videos_owner_id'))
        batch_op.drop_index(batch_op.f('idx_videos_views_desc'))
        batch_op.create_index(batch_op.f('ix_videos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_discovery_score'), ['discovery_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_video_type'), ['video_type'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_views_video_id'))
        batch_op.create_index(batch_op.f('ix_views_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_views_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_views_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_views_video_id'), ['video_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_watch_history_user_watched'))
        batch_op.create_index('ix_history_user_time', ['user_id', 'watched_at'], unique=False)
        batch_op.create_index('ix_history_video_id', ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_video_id')
        batch_op.drop_index('ix_history_user_time')
        batch_op.create_index(batch_op.f('idx_watch_history_user_watched'), ['user_id', sa.literal_column('watched_at DESC')], unique=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_id'))

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_views_video_id'))
        batch_op.drop_index(batch_op.f('ix_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_views_post_id'))
        batch_op.drop_index(batch_op.f('ix_views_id'))
        batch_op.create_index(batch_op.f('idx_views_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_videos_video_type'))
        batch_op.drop_index(batch_op.f('ix_videos_status'))
        batch_op.drop_index(batch_op.f('ix_videos_owner_id'))
        batch_op.drop_index(batch_op.f('ix_videos_id'))
        batch_op.drop_index(batch_op.f('ix_videos_discovery_score'))
        batch_op.drop_index(batch_op.f('ix_videos_created_at'))
        batch_op.create_index(batch_op.f('idx_videos_views_desc'), [sa.literal_column('views DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_videos_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_videos_discovery_score'), ['discovery_score'], unique=False)
        batch_op.create_index(batch_op.f('idx_videos_created_at_desc'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('video_interactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_video_interactions_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_video_interactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_video_interactions_id'))

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_id'))
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_country'))

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))

    with op.batch_alter_table('user_recommendation_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_recommendation_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_recommendation_profiles_id'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_column('status')

    with op.batch_alter_table('sponsored_ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsored_ads_id'))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    with op.batch_alter_table('reposts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reposts_id'))

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_endpoint'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_posts_original_post_id'))
        batch_op.drop_index(batch_op.f('ix_posts_id'))
        batch_op.drop_index(batch_op.f('ix_posts_discovery_score'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.create_index(batch_op.f('idx_posts_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payout_requests_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_status'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_requested_at'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_id'))

    with op.batch_alter_table('partner_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_leads_id'))
        batch_op.drop_index(batch_op.f('ix_partner_leads_created_at'))
        batch_op.drop_index(batch_op.f('ix_partner_leads_contact_email'))
        batch_op.drop_index(batch_op.f('ix_partner_leads_brand_name'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_likes_video_id'))
        batch_op.drop_index(batch_op.f('ix_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_likes_post_id'))
        batch_op.drop_index(batch_op.f('ix_likes_id'))
        batch_op.create_index(batch_op.f('idx_likes_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_follows_id'))
        batch_op.drop_index(batch_op.f('ix_follows_following_id'))
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follows_created_at'))
        batch_op.create_index(batch_op.f('idx_follows_following_id'), ['following_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_follows_follower_id'), ['follower_id'], unique=False)
        batch_op.alter_column('following_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('discovered_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_categories_name'))
        batch_op.drop_index(batch_op.f('ix_discovered_categories_is_approved'))
        batch_op.drop_index(batch_op.f('ix_discovered_categories_id'))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_video_id'))
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_comments_id'))
        batch_op.create_index(batch_op.f('idx_comments_video_id_created'), ['video_id', sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_title'))
        batch_op.drop_index(batch_op.f('ix_challenges_id'))

    with op.batch_alter_table('challenge_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_challenge_entries_id'))

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_achievements_id'))

    with op.batch_alter_table('watch_later', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_later_video_id'))
        batch_op.drop_index(batch_op.f('ix_watch_later_user_id'))
        batch_op.drop_index(batch_op.f('ix_watch_later_id'))

    op.drop_table('watch_later')
    # ### end Alembic commands ###
