"""add_paid_and_gold_challenge_fields

Revision ID: f463c2bc4dcf
Revises: 55ef522b3e8c
Create Date: 2026-05-05 21:54:07.267666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f463c2bc4dcf'
down_revision: Union[str, Sequence[str], None] = '55ef522b3e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_gold', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('entry_fee', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('entry_fee')
        batch_op.drop_column('is_gold')
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
